### ISSUE TITLE
BUG - Some images not showing 

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Rules.Content#101]
Hi team,

Some images in this rule https://www.ssw.com.au/rules/do-you-know-when-to-branch-in-git are not showing.

<img width="866" alt="Screen Shot 2021-02-26 at 6 43 46 PM" src="https://user-images.githubusercontent.com/12601228/109373296-d7f1ac80-7862-11eb-8c9e-c201c6d612d4.png">

I can see them in the old SharePoint: https://rules.ssw.com.au/do-you-know-when-to-branch-in-git

1. Any idea why they were not migrated properly?
2. Please investigate and fix 

[AB#60134](https://ssw.visualstudio.com/ecd18a76-dd97-4cb9-bbb4-d2edfaa0a78c/_workitems/edit/60134)

**Comment by bradystroud** [comment]
Hi @tiagov8 

> 1. Any idea why they were not migrated properly?

Done - The images were migrated fine, because the images were so thin the grey box was covering them up. Changes to the CSS fixed this.

> 2. Please investigate and fix

Done - Thin images are now visible

![Screen Shot 2021-03-18 at 8 20 16 am](https://user-images.githubusercontent.com/38869720/111546060-c8f77d80-87c2-11eb-890c-1f72e1b82c3d.png)
**Figure: Thin images visible**

Thanks,

-Brady

**Comment by tiagov8** [comment]
Hey @bradystroud 

the very first image in this rule https://www.ssw.com.au/rules/do-you-use-buffer-to-post-to-social-media is looking weird, although it looks OK if opened in a new tab: https://www.ssw.com.au/rules/static/33ed45f5a28ab813b5073ab4d6bbaeb5/e9f84/buffer_tool.jpg 

Apparently, because image's height is too small... Is this related to this issue somehow?

I could ask the Social Media team to take a larger screenshot but was hoping if we should investigate first.

**Comment by bradystroud** [comment]
Hey @tiagov8 

See my comment here on why this issue still exists.

https://github.com/SSWConsulting/SSW.Rules/issues/436#issuecomment-851158733

Thanks,

-Brady
