### ISSUE TITLE
Weird rule in Chinese

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Rules.Content#1041]
Hey @bradystroud ,
 
Any idea what happened here? https://www.ssw.com.au/rules/scrum 
And how you think we should proceed about it?

**Comment by bradystroud** [comment]
Hey Tiago,

Looks like someone wrote a rule in Chinese.
I have archived it here https://github.com/SSWConsulting/SSW.Rules.Content/pull/4594
