### ISSUE TITLE
BUG - Code blocks are not syntax highlighting

### ISSUE THREAD

**Issue by JackLeerson** [SSWConsulting/SSW.Rules.Content#118]
Cc: @bradystroud @tiagov8 

Hi team,

Code blocks should be highlighting as in Figure 1, but are white like Figure 2.

This is because they are missing the language tag in the markdown as shown in Figure 3. The white code block markdown is shown in Figure 4.

1. Add the relevant language tag to all code blocks in rules.

![image](https://user-images.githubusercontent.com/77082983/109762825-583e5600-7c45-11eb-9e77-8d94a98ea094.png)
**Figure 1: Code block on https://www.ssw.com.au/rules/rule**

![image](https://user-images.githubusercontent.com/77082983/109762838-5c6a7380-7c45-11eb-9cab-a09622b7d41f.png)
**Figure 2: Code block on https://www.ssw.com.au/rules/do-you-use-windows-integrated-authentication-connection-string-in-web-config**

![image](https://user-images.githubusercontent.com/77082983/109762847-612f2780-7c45-11eb-894c-56a7d29422ed.png)
**Figure 3: Javascript language tag present**

![image](https://user-images.githubusercontent.com/77082983/109762860-642a1800-7c45-11eb-9f39-0abf220b4416.png)
**Figure 4: Language tag not present**

[AB#60212](https://ssw.visualstudio.com/ecd18a76-dd97-4cb9-bbb4-d2edfaa0a78c/_workitems/edit/60212)

**Comment by tiagov8** [comment]
Hi @JackLeerson 

1. Can you please add this information + code examples to https://www.ssw.com.au/rules/rule ?
A list of available languages would be great

Cheers,
Tiago

**Comment by tiagov8** [comment]
> Hi @JackLeerson
> 
> 1. Can you please add this information + code examples to https://www.ssw.com.au/rules/rule ?
>    A list of available languages would be great
> 
> Cheers, Tiago

This has been done: https://ssw.com.au/rules/rule#11-code 

The rule given as example is also fixed: https://ssw.com.au/rules/do-you-use-windows-integrated-authentication-connection-string-in-web-config
