### ISSUE TITLE
Bug - PR failing ONLY on category change

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Rules.Content#122]
I've got errors on PRs that are related to rule category changes: 

https://github.com/SSWConsulting/SSW.Rules.Content/actions/runs/612029603 and https://github.com/SSWConsulting/SSW.Rules.Content/actions/runs/612021324

as per @bradystroud :

>     [Monday 2:31 PM] Brady Stroud www.ssw.com.au
>     Hey Tiago, it looks like the script that generate the history file fails when you move rules to another category

1. Please investigate and fix

**Note:** Related to Uly's https://github.com/SSWConsulting/SSW.Rules.Content/issues/121 except his PRs are simple content changes... mine are **only** if I update categories

[AB#60220](https://ssw.visualstudio.com/ecd18a76-dd97-4cb9-bbb4-d2edfaa0a78c/_workitems/edit/60220)

**Comment by tiagov8** [comment]
**Note 2:** I can't @ mention Uly here: @uly here:

<img width="781" alt="Screen Shot 2021-03-03 at 3 35 31 PM" src="https://user-images.githubusercontent.com/12601228/109887162-1c4fc480-7c36-11eb-9a1f-578e1814c714.png">

**Comment by JackLeerson** [comment]
Hi @tiagov8 

1. Can you please check that this now works.

**Comment by tiagov8** [comment]
Hi @JackLeerson

Test pass - I've updated this category today https://www.ssw.com.au/rules/rules-to-better-pcs and everything seems alright https://github.com/SSWConsulting/SSW.Rules.Content/pull/250 ;)

**Comment by JackLeerson** [comment]
Hi @tiagov8, @bradystroud 

Excellent, closing this as all errors seen have been fixed.
