### ISSUE TITLE
BUG - updated by and dates information not showing on a rule

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Rules.Content#1731]
**Hi team,**
  
https://www.ssw.com.au/rules/set-up-azure-alert-emails-on-teams-channel 

I created this rule a while ago, but only today notice that "last updated by" and the dates not showing  

1. Please investigate and fix

<img width="1163" alt="Screen Shot 2021-09-17 at 5 18 15 PM" src="https://user-images.githubusercontent.com/12601228/133865552-d609b9f4-7c29-422b-8900-c35c502a055a.png">

**Comment by christianmorfordwaitessw** [comment]
> 1. Please investigate and fix

**Done** - Rules are now showing updated by dates and information
See https://www.ssw.com.au/rules/set-up-azure-alert-emails-on-teams-channel
![image](https://user-images.githubusercontent.com/56522256/149250644-83ad1763-a6f3-4f86-a73e-b4c021c65315.png)
**Figure: Rule is now showing date information**
