### ISSUE TITLE
Rule is redirecting to an old Consulting page

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Rules.Content#179]
Team,

This rule https://www.ssw.com.au/rules/do-you-know-why-you-should-chinafy-your-app is redirecting to https://www.ssw.com.au/ssw/Consulting/Chinafy-b.aspx and giving a CodeAuditor error:

<img width="1400" alt="Screen Shot 2021-03-11 at 3 06 21 PM" src="https://user-images.githubusercontent.com/12601228/110867355-6f9bc580-827b-11eb-9766-f4e9792c80b3.png">

I am not sure WHY we have this redirect and I see no reason for it right now

1. Can we find out how this redirect was set? Maybe there is some kind of comment explaining the reason
2. Do we have others? If yes, what are they?

@UlyssesMaclaren 

3. Can we remove that rule/redirect?

--

PS. This is the final page https://www.ssw.com.au/ssw/Consulting/Chinafy-App.aspx

**Comment by UlyssesMaclaren** [comment]
sure

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

From: Tiago Araújo ***@***.***>
Sent: Friday, 12 March 2021 10:10 AM
To: ***@***.***>
Cc: Ulysses Maclaren ***@***.***>; ***@***.***>
Subject: [SSWConsulting/SSW.Rules.Content] Rule is redirecting to an old Consulting page (#179)


Team,

This rule https://www.ssw.com.au/rules/do-you-know-why-you-should-chinafy-your-app is redirecting to https://www.ssw.com.au/ssw/Consulting/Chinafy-b.aspx and giving a CodeAuditor error:

[Screen Shot 2021-03-11 at 3 06 21 PM]<https://user-images.githubusercontent.com/12601228/110867355-6f9bc580-827b-11eb-9766-f4e9792c80b3.png>

I am not sure WHY we have this redirect and I see no reason for it right now

  1.  Can we find out how this redirect was set? Maybe there is some kind of comment explaining the reason
  2.  Do we have others? If yes, what are they?

@UlyssesMaclaren<https://github.com/UlyssesMaclaren>

  1.  Can we remove that rule/redirect?

**Comment by tiagov8** [comment]
Hi @JackLeerson 

1. Please delete https://www.ssw.com.au/rules/do-you-know-why-you-should-chinafy-your-app

**Comment by tiagov8** [comment]
FYI - Not sure how but the redirect is gone and it seems the rule has its value, so no further action is required.
