### ISSUE TITLE
BUG - Broken image on rules' categories summaries

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Rules.Content#182]
Hi team,

the image on https://www.ssw.com.au/rules/rules-to-better-scrum-using-azure-devops summary is broken:
<img width="864" alt="Screen Shot 2021-03-11 at 3 43 36 PM" src="https://user-images.githubusercontent.com/12601228/110870092-a0cac480-8280-11eb-82c6-8fbdc04b4b84.png">

the image on https://www.ssw.com.au/rules/rules-to-better-google-rankings is also broken:
<img width="698" alt="Screen Shot 2021-03-11 at 4 56 16 PM" src="https://user-images.githubusercontent.com/12601228/110875604-cbba1600-828a-11eb-98e8-62a272eaa982.png">

1. Please investigate and fix

AB#60473

**Comment by tiagov8** [comment]
Found another related issue on https://www.ssw.com.au/rules/rules-to-better-inbox-management 

<img width="858" alt="Screen Shot 2021-03-15 at 2 56 58 PM" src="https://user-images.githubusercontent.com/12601228/111226779-d3d1c880-859e-11eb-8247-1c952ad182da.png">

**Comment by bradystroud** [comment]
cc: @JackLeerson 
Hi @tiagov8,

> 1. Please investigate and fix

Done - This has been fixed

![2021-04-13_14-21-18](https://user-images.githubusercontent.com/38869720/114496621-b3f7f800-9c63-11eb-81b2-8cfab7eb55c2.png)
**Figure: Image on category https://www.ssw.com.au/rules/rules-to-better-google-rankings was fixed**

Thanks,

-Brady
