### ISSUE TITLE
Remove duplicate rules

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Rules.Content#2082]
(Checked by Jack)
Cc: @JackDevAU @christianmorfordwaitessw @pierssinclairssw
  
Hi @tiagov8,
  
In relation to your comment on [Issue #300](https://github.com/SSWConsulting/SSW.Rules/issues/300#issuecomment-852533406) for SSW.Rules we have found multiple rules that have the same problem and would like to address them at the same time.

This issue seems to be because the rule has been duplicated, rewritten and redirected to the duplicated rule.

![image](https://user-images.githubusercontent.com/17246482/141217122-4c67c4fb-a7b9-4125-bf36-6e24dbf8386a.png)
**Figure: Showing the same rule duplicated and put into different folders**

- [x]  Go through the identified list of duplicated rules in the **/rules** folder below
- [x] Investigate who made these changes and why.
- [x]  Identify any further rules that are duplicated in the repository
- [x]  Compare the duplicate rules and decide which version should stay.

**NOTE:** We suspect that any folder ending in 1 is the more recent and true version of the rule as these duplicates redirect from the old uri.       

### Identified Rule Duplicates:
- do-you-backup-your-databases
- do-you-disable-connections
- do-you-do-a-quick-test-after-the-upgrade-finishes
- do-you-get-a-developer-to-test-the-migration
- do-you-have-a-mobile-friendly-website (No original rule)
- do-you-have-a-rollback-plan
- do-you-know-to-upgrade-your-third-party-tools
- do-you-know-your-migration-choices
- do-you-plan-your-additional-steps
- do-you-run-dog-food-stats-after
- do-you-run-your-dog-food-stats-before
- do-you-schedule-a-followup-meeting-after-a-spec-review (No original rule)
- do-you-turn-off-database-mirroring-before-upgrading-your-tfs-databases
- does-your-user-account-have-sql-server-system-administrator-privileges-in-sql-server
- dates-do-you-keep-date-formats-consistent-across-your-application

**Comment by tkapa** [comment]
Hey @tiagov8,

Have you managed to make any progress on this one?

**Comment by tiagov8** [comment]
@tkapa 

as per our conversation with Piers, I've marked the item to identify the rules as 'done'.

1. Please run the same script to find folders ending with "1" for "2" as well (just to make sure there aren't more)

**Comment by tiagov8** [comment]
Hi @tkapa ,

I went thorough the list of rules and found **none** that were **not** extracted from SharePoint, so I marked "who made the changes and why" as 'done'.

A curious factor is that the majority part of these rules were created by Ben Cull

**Comment by tkapa** [comment]
Hey @tiagov8,

> 1. Please run the same script to find folders ending with "2" as well (just to make sure there aren't others)  

I did manage to find a straggler:  
    https://www.ssw.com.au/rules/do-you-know-to-hyperlink-your-phone-numbers-2

**Comment by tiagov8** [comment]
Hi @tkapa ,

as per our conversation, a bunch of these rules are part of "Migration" categories. We have **3 categories for CRM migration**, **4 for SharePoint migration**, and **4 for TFS migration**.

<img width="492" alt="Screen Shot 2021-11-18 at 3 36 11 PM" src="https://user-images.githubusercontent.com/12601228/142513575-dbce5eea-9145-4935-a8d0-16cf1f2be5c1.png">

Some rules under each of these categories have the same title and URL, but were actually aimed to different versions migration, which caused the duplication. They were wrongly redirected to other rules.

For the rules that fit the scenario above I have marked as **MIGRATION CATEGORY** (not sure what to do with them, but I'd vote to only keep the most recent category version and archive all the rest)

For the others, I suggested an action in **BOLD**...

### Identified Rule Duplicates:

- **MIGRATION CATEGORY** do-you-backup-your-databases 
  - https://github.com/SSWConsulting/SSW.Rules.Content/blob/main/rules/do-you-backup-your-databases/rule.md
  - https://github.com/SSWConsulting/SSW.Rules.Content/blob/main/rules/do-you-backup-your-databases1/rule.md
  
- **MIGRATION CATEGORY** do-you-disable-connections 
  - https://github.com/SSWConsulting/SSW.Rules.Content/blob/main/rules/do-you-disable-connections/rule.md
  - https://github.com/SSWConsulting/SSW.Rules.Content/blob/main/rules/do-you-disable-connections1/rule.md

- **MIGRATION CATEGORY** do-you-do-a-quick-test-after-the-upgrade-finishes
  - https://github.com/SSWConsulting/SSW.Rules.Content/blob/main/rules/do-you-do-a-quick-test-after-the-upgrade-finishes/rule.md
  - https://github.com/SSWConsulting/SSW.Rules.Content/blob/main/rules/do-you-do-a-quick-test-after-the-upgrade-finishes1/rule.md

- **MIGRATION CATEGORY** do-you-get-a-developer-to-test-the-migration 
  - https://github.com/SSWConsulting/SSW.Rules.Content/blob/main/rules/do-you-get-a-developer-to-test-the-migration/rule.md
  - https://github.com/SSWConsulting/SSW.Rules.Content/blob/main/rules/do-you-get-a-developer-to-test-the-migration1/rule.md
  
- **NOTHING TO DO (I GUESS)** do-you-have-a-mobile-friendly-website (No original rule)
  - https://github.com/SSWConsulting/SSW.Rules.Content/blob/main/rules/do-you-have-a-mobile-friendly-website1/rule.md
     **I'VE ARCHIVED THIS RULE** https://github.com/SSWConsulting/SSW.Rules.Content/pull/2118 (replaced by https://www.ssw.com.au/rules/design-web-pages-to-work-on-mobile-and-tablets-screens-aka-responsive-web-design)

- **MIGRATION CATEGORY** do-you-have-a-rollback-plan 
  - https://github.com/SSWConsulting/SSW.Rules.Content/blob/main/rules/do-you-have-a-rollback-plan/rule.md
  - https://github.com/SSWConsulting/SSW.Rules.Content/blob/main/rules/do-you-have-a-rollback-plan1/rule.md
 
- **MIGRATION CATEGORY** do-you-know-to-upgrade-your-third-party-tools 
  - https://github.com/SSWConsulting/SSW.Rules.Content/blob/main/rules/do-you-know-to-upgrade-your-third-party-tools/rule.md
  - https://github.com/SSWConsulting/SSW.Rules.Content/blob/main/rules/do-you-know-to-upgrade-your-third-party-tools1/rule.md

- **MIGRATION CATEGORY** do-you-know-your-migration-choices
  - https://github.com/SSWConsulting/SSW.Rules.Content/blob/main/rules/do-you-know-your-migration-choices/rule.md
  - https://github.com/SSWConsulting/SSW.Rules.Content/blob/main/rules/do-you-know-your-migration-choices1/rule.md
  
- **MIGRATION CATEGORY** do-you-plan-your-additional-steps
  - https://github.com/SSWConsulting/SSW.Rules.Content/blob/main/rules/do-you-plan-your-additional-steps/rule.md
  - https://github.com/SSWConsulting/SSW.Rules.Content/blob/main/rules/do-you-plan-your-additional-steps1/rule.md

- **MIGRATION CATEGORY (NOTE: This has the number "2")**  do-you-run-dog-food-stats-after
  - https://github.com/SSWConsulting/SSW.Rules.Content/blob/main/rules/do-you-run-dog-food-stats-after/rule.md
  - https://github.com/SSWConsulting/SSW.Rules.Content/blob/main/rules/do-you-run-dog-food-stats-after2/rule.md

- **MIGRATION CATEGORY** do-you-run-your-dog-food-stats-before
  - https://github.com/SSWConsulting/SSW.Rules.Content/blob/main/rules/do-you-run-your-dog-food-stats-before/rule.md
  - https://github.com/SSWConsulting/SSW.Rules.Content/blob/main/rules/do-you-run-your-dog-food-stats-before1/rule.md
  - **WEIRD THIS RULE DOESN'T SHOW THE HISTORY** https://www.ssw.com.au/rules/run-your-dog-food-stats-before
     <img width="884" alt="Screen Shot 2021-11-18 at 4 04 03 PM" src="https://user-images.githubusercontent.com/12601228/142515929-88051809-cb06-48a5-b8bc-59cc2414ae52.png">

- **PLEASE JUST FIX THE FOLDER NAME (REMOVE "1")** do-you-schedule-a-followup-meeting-after-a-spec-review (No original rule)
  - https://github.com/SSWConsulting/SSW.Rules.Content/blob/main/rules/do-you-schedule-a-followup-meeting-after-a-spec-review1/rule.md
  - Note: THIS ONE IS NOT REDIRECTING 
    - https://www.ssw.com.au/rules/do-you-schedule-a-followup-meeting-after-a-spec-review
    - https://www.ssw.com.au/rules/do-you-schedule-a-followup-meeting-after-a-spec-review1
  
- **MIGRATION CATEGORY** do-you-turn-off-database-mirroring-before-upgrading-your-tfs-databases
  **Note: The content for this one is exactly the same**
  - https://github.com/SSWConsulting/SSW.Rules.Content/blob/main/rules/do-you-turn-off-database-mirroring-before-upgrading-your-tfs-databases/rule.md
  - https://github.com/SSWConsulting/SSW.Rules.Content/blob/main/rules/do-you-turn-off-database-mirroring-before-upgrading-your-tfs-databases1/rule.md
  
- **MIGRATION CATEGORY** does-your-user-account-have-sql-server-system-administrator-privileges-in-sql-server
  - https://github.com/SSWConsulting/SSW.Rules.Content/blob/main/rules/does-your-user-account-have-sql-server-system-administrator-privileges-in-sql-server/rule.md
  - https://github.com/SSWConsulting/SSW.Rules.Content/blob/main/rules/does-your-user-account-have-sql-server-system-administrator-privileges-in-sql-server1/rule.md
  
- **NOTHING TO DO (I DIDN'T FIND THE DUPLICATE)** [dates-do-you-keep-date-formats-consistent-across-your-application](https://www.ssw.com.au/rules/dates-do-you-keep-date-formats-consistent-across-your-application)
  - https://github.com/SSWConsulting/SSW.Rules.Content/blob/main/rules/dates-do-you-keep-date-formats-consistent-across-your-application/rule.md

- **PLEASE JUST FIX THE FOLDER NAME (REMOVE "2")** https://www.ssw.com.au/rules/do-you-know-to-hyperlink-your-phone-numbers-2
  - https://github.com/SSWConsulting/SSW.Rules.Content/blob/main/rules/do-you-know-to-hyperlink-your-phone-numbers-2/rule.md
  
--- 

PS. I have marked "Go through the identified list of duplicated rules in the /rules folder below" and "Compare the duplicate rules and decide which version should stay." as 'done'.

**Comment by tiagov8** [comment]
Hey @tkapa 

as per the thread **RE: SSW Rules - Amending duplicate rules**

1. Please double check the rules and their links and close this issue ;)

Cheers,
Tiago

**Comment by tiagov8** [comment]
Hey @tkapa 

(reminder)

1. Please double check the rules and their links and close this issue ;)
