### ISSUE TITLE
🐛Bug: Unable to log in to Netlify CMS

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Rules.Content#2148]
Cc: @adamcogan @pierssinclairssw @christianmorfordwaitessw 
  
Hi @JackDevAU,
  
Upon trying to log into the Netlify CMS, I was presented with an HTTP 500 Error. 

![image](https://user-images.githubusercontent.com/17246482/142970524-49ecc70e-9b0a-4e3f-a56d-52f79da5cf3c.png)
_**Figure: Showing HTTP 500 Error when trying to log into Netlify CMS**_

- [x] Investigate the cause of the login issue
- [ ] Fix the issue and link a PR here

**Comment by tkapa** [comment]
@christianmorfordwaitessw investigated the issue and found that there was an issue with the client secrets for SSW Rules in production. This caused the Azure function calls to fail.

- [ ] Add the secrets to the production deployment

**Comment by JackDevAU** [comment]
This has now been fixed!
