### ISSUE TITLE
🐛Bug - History missing from a rule

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Rules.Content#2152]
Cc: @pierssinclairssw @christianmorfordwaitessw  @tiagov8 
  
Hi @JackDevAU ,
  
As Tiago mentioned on my issue #2082, the rule at https://www.ssw.com.au/rules/run-your-dog-food-stats-before is missing the edit history underneath the rule name.

- [x] Investigate and fix

**Comment by JackDevAU** [comment]
cc @tiagov8 @bradystroud 

Hey @tkapa,

This is an issue with the old History.json system not correctly adding history to the json file. 

To fix this issue,
- Make any edit to the rule and when you merge to main a history will then be added

Thanks 🙂
