### ISSUE TITLE
BUG - IMPORTANT! Redirect not working

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Rules.Content#241]
Hi team,

This rule is the 1st result on Google https://www.ssw.com.au/rules/do-you-send-as-per-our-conversation-emails/

<img width="832" alt="Screen Shot 2021-03-15 at 2 36 41 PM" src="https://user-images.githubusercontent.com/12601228/111224575-e0a0ed00-859b-11eb-8d34-317d1925938f.png">

**and is giving a 404!**

<img width="561" alt="Screen Shot 2021-03-15 at 2 39 21 PM" src="https://user-images.githubusercontent.com/12601228/111224864-3ffefd00-859c-11eb-822a-b566d1f2fbd0.png">

The URL was shortened to https://www.ssw.com.au/rules/as-per-our-conversation-emails and from the [code](https://raw.githubusercontent.com/SSWConsulting/SSW.Rules.Content/main/rules/do-you-send-as-per-our-conversation-emails/rule.md) the redirect was applied but it's not working:

<img width="1035" alt="Screen Shot 2021-03-15 at 2 38 34 PM" src="https://user-images.githubusercontent.com/12601228/111224792-278ee280-859c-11eb-88ce-7409f786511e.png">

1. Please investigate and fix

Cheers,
Tiago

AB#60471

**Comment by tiagov8** [comment]
closed by mistake - then reopened.

**Comment by tiagov8** [comment]
Related: https://github.com/SSWConsulting/SSW.Rules.Content/issues/343

**Comment by bradystroud** [comment]
Reopening as this was closed because it was automatically linked to a PR.

**Comment by tiagov8** [comment]
The redirect is now working fine so no further action is required.
