### ISSUE TITLE
UI - Image Rendering Inconsistent with v1

### ISSUE THREAD

**Issue by MattGoldmanSSW** [SSWConsulting/SSW.Rules.Content#25]
# bug\_report

**Describe the bug**
The way that images are displayed in v2 is inconsistent with the way they are displayed in v1, leading to some unexpected behavior.

**To Reproduce**
1. Go to https://rules.ssw.com.au/choose-the-best-method-of-authentication-for-your-situation
2. In another tab, go to https://www.ssw.com.au/rules/choose-the-best-method-of-authentication-for-your-situation
3. Observer the difference between how the introductory image is rendered

**Expected behavior**
Images should be rendered the same dimensions (and possibly with the same decoration)

**Screenshots**
![image](https://user-images.githubusercontent.com/55862976/107824689-0046c900-6dd6-11eb-832a-eec68418ecde.png)
*Figure: Comparison of image displayed on Rules v1 and same image in same rule in v2*

**Desktop \(please complete the following information\):**

* OS: Windows 10
* Browser: Edge 
* Version: 89.0.774.23

[AB#59872](https://ssw.visualstudio.com/ecd18a76-dd97-4cb9-bbb4-d2edfaa0a78c/_workitems/edit/59872)

**Comment by christianmorfordwaitessw** [comment]
To: @MattGoldmanSSW 
Cc: @adamcogan 

Hi @MattGoldmanSSW,

We have included more options in the markdown formatting to allow for different image sizes and kept the borders grey consistent. We can't specify the image size through markdown so we have included (img-small, img-medium, img-large) tags.

```
::: img-small  
![](security-icon-ssw.jpg)  
:::  
```

![image](https://user-images.githubusercontent.com/56522256/108457458-c9d1e800-72c6-11eb-9e93-9d3f1c0c1911.png)  
**Figure: Side by side comparison of small images** 

![image](https://user-images.githubusercontent.com/56522256/108457696-3816aa80-72c7-11eb-89cf-d5829f820ed1.png)  
**Figure: Example of small, medium and large images - https://www.ssw.com.au/rules/rule**
