### ISSUE TITLE
Related Rule Contains the same URL as the Rule itself

### ISSUE THREAD

**Issue by tribalthirst** [SSWConsulting/SSW.Rules.Content#3705]
https://www.ssw.com.au/rules/dones-do-you-include-useful-details-in-your-done-email 

Look at the related rules section.

<img width="592" alt="image" src="https://user-images.githubusercontent.com/1544737/181117996-6fe47329-d750-4ae1-bad7-223e4dd15bb7.png">

**Comment by tiagov8** [comment]
Thanks @tribalthirst 

This has been fixed:
<img width="717" alt="Screen Shot 2022-12-07 at 12 22 07 PM" src="https://user-images.githubusercontent.com/12601228/206287572-99ccc7a4-cf98-4bde-a395-59e36b745f5a.png">
