### ISSUE TITLE
Adding a slash to the end of a previously named rule causes redirect to stop working

### ISSUE THREAD

**Issue by pierssinclairssw** [SSWConsulting/SSW.Rules.Content#392]
@bradystroud @JackLeerson 
# bug\_report

**Describe the bug**
Adding a slash to the end of a previously named rule causes redirect to stop working

**To Reproduce** Steps to reproduce the behavior: 1. Go to '...' 2. Click on '....' 3. Scroll down to '....' 4. See error
1. Navigate to https://www.ssw.com.au/rules/do-you-use-the-best-static-site-generator/
2. You see a 404 error.

**Expected behavior**
You should see the updated rule and the new url for it.

**Screenshots** If applicable, add screenshots to help explain your problem.

![MicrosoftTeams-image (25)](https://user-images.githubusercontent.com/79821522/112391617-4afc1f00-8d4c-11eb-9f47-0a80efdde27f.png)
https://user-images.githubusercontent.com/79821522/112391570-39b31280-8d4c-11eb-9a62-d4dde1c061b2.mov

**Desktop \(please complete the following information\):**

* OS: Windows 10
* Browser Chrome and Edge

**Additional context** Add any other context about the problem here.

**Comment by tiagov8** [comment]
Hey @bradystroud 

Is this the same as https://github.com/SSWConsulting/SSW.Rules/issues/523 ?

**Comment by bradystroud** [comment]
Hey @tiagov8

Yes - same problem 

Hey @pierssinclairssw 

Closing as its fixed by https://github.com/SSWConsulting/SSW.Rules/issues/523
