### ISSUE TITLE
🐛 Archived rule missing "archived" box

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Rules.Content#4376]
Hey @bradystroud 

1. Any idea why this rule is not showing the "archived" box at the top?
https://ssw.com.au/rules/when-to-create-team-project-and-azure-devops-portal 

This is the PR I archived it: https://github.com/SSWConsulting/SSW.Rules.Content/pull/4317 
And this was an attempt to fix it by reducing reason: https://github.com/SSWConsulting/SSW.Rules.Content/pull/4360 

Cheers,

**Comment by bradystroud** [comment]
Hey @tiagov8 


> 1. Any idea why this rule is not showing the "archived" box at the top?
https://ssw.com.au/rules/when-to-create-team-project-and-azure-devops-portal

Done - I have fixed this in this PR
https://github.com/SSWConsulting/SSW.Rules.Content/pull/4444

The archived field is `archivedreason` not `archived`

Sorry, I should have picked this up earlier.
