### ISSUE TITLE
Embedded tweets not displaying

### ISSUE THREAD

**Issue by jackreimers** [SSWConsulting/SSW.Rules.Content#5453]
Hi @bradystroud ,
  
The embedded tweets on https://ssw.com.au/rules/make-newcomers-feel-welcome/ are not displaying.

**Comment by bradystroud** [comment]
Hey @jackreimers 

I cant reproduce this, it seems to be working on both the category and rule view.

Can you add some screenshots? (as per https://www.ssw.com.au/rules/report-bugs-and-suggestions)

![image](https://user-images.githubusercontent.com/38869720/235812964-78567daa-c901-4e98-9120-9a144189deef.png)
**✅ Figure: Category view - LGTM**

![image](https://user-images.githubusercontent.com/38869720/235812998-04f8ddae-4cd3-4f63-8d7a-7ee180edf179.png)
**✅ Figure: Rule view**

**Comment by jackreimers** [comment]
@bradystroud I can't reproduce it anymore either, they're both displaying correctly

**Comment by bradystroud** [comment]
Closing as we can't reproduce
