### ISSUE TITLE
Updating the Unit test rule for "popular test framework"

### ISSUE THREAD

**Issue by OsirisTerje** [SSWConsulting/SSW.Rules.Content#5644]
Cc: @adamcogan 
  
Hi Team,
  
The text for XUnit and NUnit in this rule is outdated:  https://ssw.com.au/rules/the-most-popular-unit-testing-frameworks-for-net-core-applications/  

1. Make XUnit more precise

2. Add info on NUnit modernization (last 10 years)

3. Add new point on mixing frameworks

**Comment by Hona** [comment]
Looks like this can be closed now via your PR, correct @OsirisTerje ?
