### ISSUE TITLE
🔗 Broken links for images 

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Rules.Content#5772]
Cc: @tombui99 @adamcogan @Aibono1225 
  
Hi @bradystroud 
  
as per our conversation on Teams,

The links to the SSW background images examples are broken on
https://www.ssw.com.au/rules/browser-add-branding/

It seems like the images are in the right place

* https://github.com/SSWConsulting/SSW.Rules.Content/blob/main/rules/browser-add-branding/light-ssw-wallpaper.jpg
* https://github.com/SSWConsulting/SSW.Rules.Content/blob/main/rules/browser-add-branding/dark-ssw-wallpaper.png

- [x] Please investigate and fix

<img width="968" alt="Screenshot 2023-06-09 at 10 25 49 AM" src="https://github.com/SSWConsulting/SSW.Rules.Content/assets/12601228/a65b762d-9b1f-4869-aced-bd5ce066649c">

**Comment by Aibono1225** [comment]
Done ⭐ the links can be opened now
