### ISSUE TITLE
Missing image on rule "Appointments - Do you make your Teams meetings easy to find?"

### ISSUE THREAD

**Issue by zacharykeeping** [SSWConsulting/SSW.Rules.Content#7015]
Cc: @AshAnil 
  
Hi team,
  
As found in a CodeAuditor scan the rule at [Appointments - Do you make your Teams meetings easy to find?](https://www.ssw.com.au/rules/do-you-make-your-team-meetings-easy-to-find/), the rule is missing an image as referenced in change #6921. I'd try to add a new image here myself but I don't have access to the Admin Center.

<img width="718" alt="Screenshot 2023-10-18 at 9 27 52 am" src="https://github.com/SSWConsulting/SSW.Rules.Content/assets/11418832/7e492ba9-424d-4f05-98ca-82a22f574c22">

**Figure: The image here is missing. "Teams" is also misspelt.**

1. Upload a new image for this section.

2. Fix the misspelt "Temas" to "Teams"

**Comment by JackDevAU** [comment]
Closing as its been done!
