### ISSUE TITLE
🐛 BUG - Several broken images on Rules today!

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Rules.Content#7292]
Cc: @adamcogan @BrookJeynes @Harry-Ross @tombui99 
  
Hi @bradystroud @JackDevAU 
  
Navigating through some rules today I've found dozens of broken images everywhere. 
**Note:** I know these are images that used to work fine before, so definitely not something to be fixed on each rule individually.

- [ ] 1. Please investigate and fix

Example: https://www.ssw.com.au/rules/follow-up-effectively/
This rule currently has 11 broken images, and 2 working images.

But if you look at [a whole category](https://www.ssw.com.au/rules/rules-to-better-software-consultants-working-in-a-team/) will you see many more broken...

This video shows a strange behaviour... first it seems like the images are not loaded in high quality, but will appear, but then they just show as broken.

https://github.com/SSWConsulting/SSW.Rules.Content/assets/12601228/411b2760-7427-45de-a8a7-0b11e55b8b1e

<img width="1039" alt="Screenshot 2023-11-21 at 12 37 07 PM" src="https://github.com/SSWConsulting/SSW.Rules.Content/assets/12601228/30b238d1-903c-4138-968c-a47b7ff5c422">

**Comment by JackDevAU** [comment]
This has a temporary fix - We have reverted the build that broke the images. For the moment this issue has been resolved. I'll still look into it before the next release of Rules.

**Comment by JackDevAU** [comment]
This has now been fixed with release 106
