### ISSUE TITLE
🐛 Broken images on "Your SSW password" page

### ISSUE THREAD

**Issue by 2fernandez** [SSWConsulting/SSW.Rules.Content#7295]
Cc: @Dhruv-0987 @chrisschultzssw @tiagov8 

Related pull request: 
https://github.com/SSWConsulting/SSW.Rules.Content/pull/7291

**Hi Dhruv,**

It appears that the images are broken on the last commit you made to the rule:
https://www.ssw.com.au/rules/using-mfa/

- [x] Can you please change the name of the images
- [x] Re-upload and commit new files

Thanks

**Comment by 2fernandez** [comment]
@tiagov8 @chrishoogwerf 

- I no longer see this issue on this page.
- Very likely be fixed via another PR or there was a delay in the pipeline update.

Closing issue.

**Comment by tiagov8** [comment]
Hey @2fernandez 

As per our conversation on Teams, the marked as "completed" tasks above are **incorrect**

1. Please fix

**Tip for next time:** Include screenshots for broken images and things like this
