### ISSUE TITLE
Content updates on https://www.ssw.com.au/rules/management-do-you-use-just-in-time-speccing

### ISSUE THREAD

**Issue by UlyssesMaclaren** [SSWConsulting/SSW.Rules.Content#742]
CC @pierssinclairssw @adamcogan 

Hi @jaydenalchin

On https://www.ssw.com.au/rules/management-do-you-use-just-in-time-speccing

1. Add notes and links to:
* Emergent Architecture
* Documentation rules
* Tech debt
* Low code

2. Also add back into category. (When i changed the URL, it lost the rules category for this rule)

3. Add an image to represent the rule. Liase with Piers for this

**Comment by pierssinclairssw** [comment]
> 2. Also add back into category. (When i changed the URL, it lost the rules category for this rule)
Done - Fixed the broken category.

To clarify this issue these notes relate to the following rules

- Emergent Architecture: I am unsure, @UlyssesMaclaren please clarify which rule this relates to
- Documentation rules: https://www.ssw.com.au/rules/awesome-documentation
- Tech debt: https://www.ssw.com.au/rules/technical-debt
- Low code: I am unsure, @UlyssesMaclaren please clarify which rule this relates to

**Comment by jaydenalchin** [comment]
Additional notes as per my discussion with Piers and Uly: 

This rule is linked to the ideas of emergent architecture, keeping tech debt low. We currently haven’t found an emergent architecture rule to link to here. Need clarification regarding where Low Code fits in. 

> 3. Add an image to represent the rule.

This should be some image regarding emergent architecture / just-in-time speccing.

**Comment by jaydenalchin** [comment]
To: @pierssinclairssw 
1. Add a section to Awesome Documentation about alternatives and technical decision making. 

To: @calumjs 
1. Create a new rule for Rules to Better Power Apps about why you use Low Code. This should be #1 in Rules to Better Power Apps **and** Rules to Better Power Platform. 

To Myself, 
1. Change from "Superior Documentation" to "Awesome Documentation" 
2. Finish updates to rule for just-in-time speccing.

**Comment by jaydenalchin** [comment]
> Change from "Superior Documentation" to "Awesome Documentation"
Finish updates to rule for just-in-time speccing.

**Done!** The rule  https://www.ssw.com.au/rules/management-do-you-use-just-in-time-speccing has been updated

**Comment by pierssinclairssw** [comment]
> 1. Add a section to Awesome Documentation about alternatives and technical decision making.
Done - Updated the rule with an alternative solutions section

**Comment by tiagov8** [comment]
Hey @UlyssesMaclaren 

Can this Issue from May 2021 be closed?

**Comment by UlyssesMaclaren** [comment]
Hi @tiagov8 
Yes it looks like it's all done
