### ISSUE TITLE
📈 Rule - EF Core - Do you use migration bundles to update your DB?

### ISSUE THREAD

**Issue by danielmackay** [SSWConsulting/SSW.Rules.Content#7583]

**Comment by ricksu978** [comment]
I had firewall problem when I use EF migration bundles to update Azure DB as part of GitHub Actions (CI/CD pipeline).

I ended up generating migration SQL script, and use [azure/sql-action](https://github.com/Azure/sql-action?tab=readme-ov-file#deploy-sql-scripts-to-an-azure-sql-database-with-a-temporary-firewall-rule) to run the script with temporary firewall rule.

**Comment by danielmackay** [comment]
This is mentioned as part of the https://www.ssw.com.au/rules/use-code-migrations/ rule.

**Comment by danielmackay** [comment]
> I had firewall problem when I use EF migration bundles to update Azure DB as part of GitHub Actions (CI/CD pipeline).
> 
> I ended up generating [Idempotent SQL scripts](https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/applying?tabs=dotnet-core-cli#idempotent-sql-scripts) (`dotnet ef migrations script --idempotent `), and use [azure/sql-action](https://github.com/Azure/sql-action?tab=readme-ov-file#deploy-sql-scripts-to-an-azure-sql-database-with-a-temporary-firewall-rule) action to run the script with temporary firewall rule.
> 
> Any better workaround?

You're still running the DB updates via GitHub actions.  How is generating the script any different?
