### ISSUE TITLE
BUG - Images size on "add or remove someone from conversations" rule

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Rules.Content#790]
Cc: < @pierssinclairssw @calumjs @bradystroud >
  
Hi team,
  
This rule https://www.ssw.com.au/rules/do-you-know-how-to-add-or-remove-someone-from-the-conversation images are going over the limits of the content area (desktop screen)

<img width="1570" alt="Screen Shot 2021-05-10 at 10 45 03 AM" src="https://user-images.githubusercontent.com/12601228/117702025-cf7bf300-b17c-11eb-90bd-253b620120e6.png">

1. Please investigate and fix 
2. I believe this wasn't happening some weeks ago... any recent changes to the CSS (behaviour of the images)?

Tip: This piece of CSS should be present for any screen size, not only under 768px:
<img width="507" alt="Screen Shot 2021-05-10 at 10 45 43 AM" src="https://user-images.githubusercontent.com/12601228/117702115-f2a6a280-b17c-11eb-8630-649972407a8c.png">

**Comment by pierssinclairssw** [comment]
Hi @tiagov8 ,

> 1. Please investigate and fix
Done - This is a known issue when users upload images using GitHub copy/paste instead of putting the image in the rule folder. Netlify CMS will fix it.
> 2. I believe this wasn't happening some weeks ago... any recent changes to the CSS (behaviour of the images)?
To my knowledge, this issue has always happened. However, it only happens if you copy/paste in GitHub.

**Comment by bradystroud** [comment]
cc: @christianmorfordwaitessw 
Hi @tiagov8,

> 1. Please investigate and fix

Done - This was the same problem as this issue https://github.com/SSWConsulting/SSW.Rules/issues/433
