### ISSUE TITLE
♻️ Resolve conflicts on SAFe rules (folder changed in a separated PR)

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Rules.Content#8360]
Cc: @bradystroud @BrookJeynes @Aibono1225 @NadeekaJK @JackDevAU 
  
Hi team
  
There are 7 PRs from @Marxoz are pending conflicts... Resolving them is disabled to me...

I believe the cause of the conflicts if this other (approved) PR where the folder names where changed: https://github.com/SSWConsulting/SSW.Rules.Content/pull/8357   
I think I shouldn't have approved it first 😫

- [x] 1. Resolve the conflics
- [x] 2. Review and approve all PRs from https://github.com/SSWConsulting/SSW.Rules.Content/pulls/Marxoz

![Image](https://github.com/SSWConsulting/SSW.Rules.Content/assets/12601228/727e346f-34ce-4d26-a0a1-1daaa6674bc5)

![Image](https://github.com/SSWConsulting/SSW.Rules.Content/assets/12601228/96bfb525-5331-44e7-98c3-d5d8fcc36d9a)

**Comment by JackDevAU** [comment]
Done
